services:
  - type: web
    name: micasita-ai-backend
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_EMAIL_SENDER
        sync: false
      - key: USD_TO_PEN
        sync: false
